sudo: required
services:
  - docker 

before_install: 
  - docker build -t jibsan94/docker-react -f Dockerfile.dev .

script:  
  - docker run -e CI=true jibsan94/docker-react npm run test

deploy:
  provider: elastickbeanstalk
  region: "eu-west-3"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-west-3-137720646516"
  bucket_path: "frontend"
  on:
    branch:  master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"